<?php
define("INDEX","http://localhost/Admin/frontend/index.php");
define("PRODUCTS","http://localhost/Admin/frontend/products");
define("SHOP","http://localhost/Admin/frontend/shop.php");
define("DIST","http://localhost/Admin/dist");
define("PLUGIN","http://localhost/Admin/plugins");
define("LOGOUT","http://localhost/Admin/frontend/logout.php");
define("LOGIN","http://localhost/Admin/frontend/login.php");
define("REG","http://localhost/Admin/frontend/register.php");
define("CSS","http://localhost/Admin/frontend/css");
define("JS","http://localhost/Admin/frontend/js");
define("CART","http://localhost/Admin/frontend/cart/shop-cart.php");
define("WISH","http://localhost/Admin/frontend/cart/wishlist.php");
define("IMG","http://localhost/Admin/frontend/img");
define("CHECKOUT","http://localhost/Admin/frontend/cart/checkout.php");
define("BLOG_D","http://localhost/Admin/frontend/blog-details.php");
define("BLOG","http://localhost/Admin/frontend/blog.php");
define("CONTACT","http://localhost/Admin/frontend/contact.php");
define("ORDERS","http://localhost/Admin/frontend/cart/track_order.php");
define("ADMIN","http://localhost/Admin/admin_index.php");
define("HOME","http://localhost/Admin/frontend/index.php");
?>